apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: phpldapadmin
  name: phpldapadmin
spec:
  type: NodePort
  ports:
  - name: "8888"
    port: 8888
    targetPort: 80
    nodePort: 30001
  selector:
    io.kompose.service: phpldapadmin
status:
  loadBalancer: {}
